tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              width: 50
              validate:
                - required
          -
            handle: price
            field:
              type: money
              display: Price
              save_zero_value: true
              listable: hidden
              width: 50
              instructions_position: above
              visibility: visible
              always_save: false
              validate:
                - required
          -
            handle: description
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: Description
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: photo
            field:
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: photo
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: product_type
            field:
              type: button_group
              display: 'Product Type'
              options:
                physical: Physical
                digital: Digital
              default: physical
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: downloadable_asset
            field:
              type: assets
              mode: grid
              display: 'Downloadable Asset'
              container: assets
              if:
                root.product_type: 'equals digital'
          -
            handle: download_limit
            field:
              type: integer
              display: 'Download Limit'
              instructions: "If you'd like to limit the amount if times this product can be downloaded, set it here. Keep it blank if you'd like it to be unlimited."
              if:
                root.product_type: 'equals digital'
          -
            handle: tax_category
            field:
              type: tax_category
              display: 'Tax Category'
              max_items: 1
              mode: select
title: Product
